# Generated by Django 3.0.4 on 2020-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("overall_rank", models.IntegerField()),
                ("score", models.FloatField()),
                ("gdp_per_capita", models.FloatField()),
                ("social_support", models.FloatField()),
                ("healthy_life_expectancy", models.FloatField()),
                ("freedom_to_make_life_choices", models.FloatField()),
                ("generosity", models.FloatField()),
                ("perceptions_of_corruption", models.FloatField()),
            ],
        ),
    ]
